In [1]:
import numpy as np

In [9]:
array1=[23,45,18]
num=np.array(array1)
print(num)

[23 45 18]


In [15]:
np.random.rand(2,3)

array([[0.58950288, 0.35904956, 0.34220401],
       [0.14725135, 0.62178504, 0.46012993]])

In [16]:
np.random.random(size=2)

array([0.50853702, 0.93331273])

In [19]:
np.random.randint(1,101)

array([67, 58, 58, 45, 52, 90, 55, 39, 76, 32, 20, 60, 21, 34, 59,  8, 41,
       10, 82, 56,  1, 93, 92, 93, 12, 97, 81, 71, 30, 60, 60,  1, 39, 37,
        8, 67, 54, 90, 57, 73, 23, 80,  4, 94, 53, 64, 54, 76, 60, 55, 84,
        9, 91, 90, 72, 87, 13, 44, 35, 21, 17, 96, 79, 85, 53, 76,  3, 26,
       70, 72, 26, 52, 15, 61, 37, 58,  1, 44, 10, 98, 25, 33, 47,  4, 23,
       94, 21, 14, 15, 14, 35, 58, 95, 29, 34, 42, 95, 67, 70, 14])

# 

In [24]:
np.arange(1,10,5)

array([1, 6])

In [28]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
np.arange(100,0,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [32]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [37]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
matrix=np.empty((3,3),int)
print(matrix)

[[          0           0 -1032344592]
 [        573 -1032347280         573]
 [-1032345552         573         114]]


In [43]:
matrix=np.full((3,3),10)
print(matrix)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [44]:
np.identity(50)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [56]:
arr=np.arange(2,21)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [57]:
sample_array=np.arange(2,10)
print(sample_array[4])

6


In [3]:
import numpy as np 

In [4]:
np.linspace(0,6)

array([0.        , 0.12244898, 0.24489796, 0.36734694, 0.48979592,
       0.6122449 , 0.73469388, 0.85714286, 0.97959184, 1.10204082,
       1.2244898 , 1.34693878, 1.46938776, 1.59183673, 1.71428571,
       1.83673469, 1.95918367, 2.08163265, 2.20408163, 2.32653061,
       2.44897959, 2.57142857, 2.69387755, 2.81632653, 2.93877551,
       3.06122449, 3.18367347, 3.30612245, 3.42857143, 3.55102041,
       3.67346939, 3.79591837, 3.91836735, 4.04081633, 4.16326531,
       4.28571429, 4.40816327, 4.53061224, 4.65306122, 4.7755102 ,
       4.89795918, 5.02040816, 5.14285714, 5.26530612, 5.3877551 ,
       5.51020408, 5.63265306, 5.75510204, 5.87755102, 6.        ])

In [11]:
m=np.empty((3,3),int)
m

array([[        0,         1,         0],
       [      508,       816,         0],
       [      768,       191, 170483037]])

In [15]:
m1=np.eye(10)
m1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])