###### LIST

In [1]:
import numpy as np

In [9]:
array1=[23,45,18]
num=np.array(array1)
print(num)

[23 45 18]


In [15]:
np.random.rand(2,3)

array([[0.58950288, 0.35904956, 0.34220401],
       [0.14725135, 0.62178504, 0.46012993]])

In [16]:
np.random.random(size=2)

array([0.50853702, 0.93331273])

In [19]:
np.random.randint(1,101,100)

array([67, 58, 58, 45, 52, 90, 55, 39, 76, 32, 20, 60, 21, 34, 59,  8, 41,
       10, 82, 56,  1, 93, 92, 93, 12, 97, 81, 71, 30, 60, 60,  1, 39, 37,
        8, 67, 54, 90, 57, 73, 23, 80,  4, 94, 53, 64, 54, 76, 60, 55, 84,
        9, 91, 90, 72, 87, 13, 44, 35, 21, 17, 96, 79, 85, 53, 76,  3, 26,
       70, 72, 26, 52, 15, 61, 37, 58,  1, 44, 10, 98, 25, 33, 47,  4, 23,
       94, 21, 14, 15, 14, 35, 58, 95, 29, 34, 42, 95, 67, 70, 14])

In [28]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
np.arange(100,0,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [32]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [37]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
matrix=np.empty((3,3),int)
print(matrix)

[[          0           0 -1032344592]
 [        573 -1032347280         573]
 [-1032345552         573         114]]


In [43]:
matrix=np.full((3,3),10)
print(matrix)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [44]:
np.identity(50)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [56]:
arr=np.arange(2,21)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [57]:
sample_array=np.arange(2,10)
print(sample_array[4])

6


In [2]:
avg=[12,1,0,4,10000]
avg.sort()
avg

[0, 1, 4, 12, 10000]

In [5]:
avg=[12,1,0.1,10]
avg[-1]

10

In [6]:
avg=[100,10,2,100]
avg.reverse()
avg

[100, 2, 10, 100]

In [7]:
avg[1:-3]

[]

In [10]:
avg=[1,10,0.1,200,100,2000]
avg[-1]

2000

In [13]:
avg[:][3:-1]

[200, 100]

In [14]:
avg[::1]

[1, 10, 0.1, 200, 100, 2000]

In [20]:
avg[::4]

[1, 100]

In [26]:
avg.pop(2)

0.1

In [29]:
avg="20","12","2003"
sep=':'
sep.join(avg)

'20:12:2003'

In [31]:
sng="???sng????png???"
sng.strip("?")

'sng????png'

In [35]:
avg=[100,1,0.2]
max(avg)

100

In [37]:
min(avg)

0.2

In [40]:
avg.clear()
avg

[]

In [44]:
str1=[13,23,55,2.2]
str1.append(24)
str1

[13, 23, 55, 2.2, 24]

In [51]:
str1.insert(0,4)
str1

[4, 4, 0, 13, 0, 23, 0, 0, 55, 2.2, 24]

In [54]:
print (13 in str1)

True


In [55]:
str1.count(4)

2

In [56]:
str1[2]

0

In [65]:
ang=["a1","a2","a5"]
ang.pop(2)

'a5'

###### TUPLE

In [77]:
str10=("st1","st2","st3")
type(str10)

tuple

In [81]:
item=("beta","alpha","theta")
sorted(item)

['alpha', 'beta', 'theta']

In [82]:
print("beta" in item)

True


In [83]:
a=10
print(item*a)

('beta', 'alpha', 'theta', 'beta', 'alpha', 'theta', 'beta', 'alpha', 'theta', 'beta', 'alpha', 'theta', 'beta', 'alpha', 'theta', 'beta', 'alpha', 'theta', 'beta', 'alpha', 'theta', 'beta', 'alpha', 'theta', 'beta', 'alpha', 'theta', 'beta', 'alpha', 'theta')


In [84]:
print(item*2)

('beta', 'alpha', 'theta', 'beta', 'alpha', 'theta')


In [87]:
len(item)

3

In [92]:
item2=("alpha","beta","theta",["teta","sesa"])
item2[3].append(230)
item2

('alpha', 'beta', 'theta', ['teta', 'sesa', 230])

In [93]:
item.count("alpha")

1

In [94]:
item2.index("alpha")

0

In [95]:
item2[:]

('alpha', 'beta', 'theta', ['teta', 'sesa', 230])

In [100]:
len(item2)

4

In [106]:
tel=item+item2
tel

('beta', 'alpha', 'theta', 'alpha', 'beta', 'theta', ['teta', 'sesa', 230])

##### DICTIONARY

In [114]:
items={"alpha":13,"beta":23,"theta":34}
items["delta"]=56
print(items)


{'alpha': 13, 'beta': 23, 'theta': 34, 'delta': 56}


In [118]:
items={"alpha":13,"beta":23,"theta":34}
del items["alpha"]
print(items)

{'beta': 23, 'theta': 34}


In [119]:
del items["theta"]
print(items)

{'beta': 23}


In [120]:
len(items)

1

In [121]:
str(items)

"{'beta': 23}"

In [122]:
type(items)

dict

In [124]:
items.clear()
items

{}

In [127]:
items1={"alpha":13,"beta":23,"theta":34}
print(items1.get("alpha"))

13


In [128]:
print(items1.get(23))

None


In [135]:
data=("alpha","beta","theta")
dictionary=dict.fromkeys(data,237)
print(dictionary)

{'alpha': 237, 'beta': 237, 'theta': 237}


In [138]:
dictionary["deltha"]=23
print(dictionary)

{'alpha': 237, 'beta': 237, 'theta': 237, 'deltha': 23}


In [142]:
del dictionary["deltha"]
print(dictionary)

{'beta': 237, 'theta': 237}


##### LIST COMPREHENSION

In [146]:
dta=[12,45,54,878,90]
for bh in dta:
    print(bh*3-5)

31
130
157
2629
265


In [152]:
alphaa=["theta","delta","beta"]
dtda=[v[0] for v in alphaa]
dtda

['t', 'd', 'b']

In [166]:
data2="THE boy is Went at 120 spend of 1000"
frnd=[int(i) for i in data2.split() if i.isdigit()==True]
frnd


[120, 1000]

In [165]:
frnd=[str(j) for j in data2.split() if j.isupper()==True]
frnd

['THE']

In [168]:
ddt=[k for k in data2 if k in 'aeiouAEIOU']
ddt

['E', 'o', 'i', 'e', 'a', 'e', 'o']

In [173]:
d=[10 if data12=='THE' else 20 if data12=='is' else 40 for data12 in data2 ]
dta

[12, 45, 54, 878, 90]

In [1]:
tel=["dam","stel","tela","alta"]
product= [10 if i =="dam" else 40 if i=="stel" else 50 if i=="tela"else 20 for i in tel]
print(product)

[10, 40, 50, 20]


###### FUNCTION

In [7]:
def additions(a,b):
    add=a+b
    return(add)
them=additions(2,4)
print(them)

    

6


In [16]:
def argsm(num1,num2):
    print(num1)
    print(num2)
num1=1
num2=2
argsm(num2,num1)

2
1


In [21]:
def arm(name,nam2,name3,age=21):
    print(name,age)
    print(nam2,age)
    print(name3,age)
arm("bhuvi","jaya","avi")

bhuvi 21
jaya 21
avi 21


In [32]:
def adds(*num):
    add=0
    for vs in num:
        add=add+vs
    print(add)
adds(23,452,345,12345678,1111,11,111111,12345678)


24804409
